# Generated by Django 3.2.4 on 2021-06-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesent', models.DateTimeField(verbose_name='time sent')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
