# Generated by Django 4.1.6 on 2023-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='icon',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
    ]
